//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NMADesk.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class ACCIDENTE
    {
        public decimal ID_ACCIDENTE { get; set; }
        public string SEVERIDAD_ACC { get; set; }
        public decimal CANT_AFECTADO { get; set; }
        public string DESC_ACCID { get; set; }
        public decimal EMPLEADOS_RUT_EMPL { get; set; }
    
        public virtual EMPLEADOS EMPLEADOS { get; set; }
    }
}
