//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NMADesk.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class AGENDA
    {
        public AGENDA()
        {
            this.SERVICIO = new HashSet<SERVICIO>();
        }
    
        public decimal ID_AGENDA { get; set; }
        public System.DateTime FECHA_AGEN { get; set; }
        public System.DateTime FECHA_REALI { get; set; }
        public string LUGAR { get; set; }
        public decimal PROFESIONAL_RUT_PROF { get; set; }
        public string STAT_AGEN { get; set; }
    
        public virtual PROFESIONAL PROFESIONAL { get; set; }
        public virtual ICollection<SERVICIO> SERVICIO { get; set; }
    }
}
