//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NMADesk.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class CAPACITACION
    {
        public CAPACITACION()
        {
            this.DETALLE_CAP = new HashSet<DETALLE_CAP>();
        }
    
        public decimal ID_CAP { get; set; }
        public System.DateTime FECHA_CAP { get; set; }
        public string TEMA_CAP { get; set; }
        public decimal SERV_DETALLE_ID_SERV_DETALLE { get; set; }
        public decimal TIPO_CAP_ID_TIP_CAP { get; set; }
        public string STAT_CAP { get; set; }
    
        public virtual SERV_DETALLE SERV_DETALLE { get; set; }
        public virtual TIPO_CAP TIPO_CAP { get; set; }
        public virtual ICollection<DETALLE_CAP> DETALLE_CAP { get; set; }
    }
}
