//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NMADesk.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class CHECKLIST
    {
        public decimal ID_CHECKLIST { get; set; }
        public string RUBRO_CLI { get; set; }
        public string RESUL_VISI { get; set; }
        public string MEJORAS { get; set; }
        public System.DateTime FECHA_CHECKLIST { get; set; }
        public string ACT_NECES { get; set; }
        public string PROBLEM_SEG { get; set; }
        public decimal VISITA_TERR_ID_VISITA { get; set; }
    
        public virtual VISITA_TERR VISITA_TERR { get; set; }
    }
}
