//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NMADesk.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class DETALLE_SERV
    {
        public decimal ID_D_SERV { get; set; }
        public string TIPO_SERV { get; set; }
        public string NOM_SERV { get; set; }
        public decimal MENSUALIDAD_S { get; set; }
        public decimal PAGO_EXT { get; set; }
        public string ADICIONAL { get; set; }
        public decimal CONTRATO_ID_CONTRATO { get; set; }
    
        public virtual CONTRATO CONTRATO { get; set; }
    }
}
