//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NMADesk.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class DETALLE_FACT
    {
        public decimal ID_DET_FAC { get; set; }
        public decimal TOT_CAP { get; set; }
        public decimal TOT_ASES { get; set; }
        public decimal TOT_VIST { get; set; }
        public Nullable<decimal> SERV_ADIC { get; set; }
        public decimal FACTURA_ID_FACT { get; set; }
        public Nullable<decimal> MON_TOT_FACT { get; set; }
    
        public virtual FACTURA FACTURA { get; set; }
    }
}
