//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NMADesk.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class EMPLEADOS
    {
        public EMPLEADOS()
        {
            this.ACCIDENTE = new HashSet<ACCIDENTE>();
        }
    
        public decimal RUT_EMPL { get; set; }
        public string DV_EMPL { get; set; }
        public string NOM_EMPL { get; set; }
        public string AP_EMPL { get; set; }
        public decimal CANT_CAP { get; set; }
        public decimal CLIENTE_RUT_CLI { get; set; }
        public string STAT_EMPL { get; set; }
    
        public virtual ICollection<ACCIDENTE> ACCIDENTE { get; set; }
        public virtual CLIENTE CLIENTE { get; set; }
    }
}
