//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NMADesk.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class FACTURA
    {
        public FACTURA()
        {
            this.DETALLE_FACT = new HashSet<DETALLE_FACT>();
        }
    
        public decimal ID_FACT { get; set; }
        public System.DateTime FECHA_EMISION { get; set; }
        public string RAZ_SOC_EMIS { get; set; }
        public decimal RUT_CLI_FACT { get; set; }
        public decimal RUT_EMIS { get; set; }
        public string DIRECCION_CLI { get; set; }
        public decimal MONTO_PAG { get; set; }
    
        public virtual ICollection<DETALLE_FACT> DETALLE_FACT { get; set; }
    }
}
