//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NMADesk.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class MENU_ROL
    {
        public decimal ID_MENU { get; set; }
        public string DESC_MENU { get; set; }
        public decimal ROL_ID_ROL { get; set; }
    
        public virtual ROL ROL { get; set; }
    }
}
