//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NMADesk.BD
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class NMADeskEntities : DbContext
    {
        public NMADeskEntities()
            : base("name=NMADeskEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<ACCIDENTE> ACCIDENTE { get; set; }
        public DbSet<AGENDA> AGENDA { get; set; }
        public DbSet<ASESORIA> ASESORIA { get; set; }
        public DbSet<AUDITORIAUSER> AUDITORIAUSER { get; set; }
        public DbSet<CAPACITACION> CAPACITACION { get; set; }
        public DbSet<CHECKLIST> CHECKLIST { get; set; }
        public DbSet<CLIENTE> CLIENTE { get; set; }
        public DbSet<CONTRATO> CONTRATO { get; set; }
        public DbSet<DETALLE_CAP> DETALLE_CAP { get; set; }
        public DbSet<DETALLE_FACT> DETALLE_FACT { get; set; }
        public DbSet<DETALLE_SERV> DETALLE_SERV { get; set; }
        public DbSet<EMPLEADOS> EMPLEADOS { get; set; }
        public DbSet<EMPRESA> EMPRESA { get; set; }
        public DbSet<ESTADO> ESTADO { get; set; }
        public DbSet<FACTURA> FACTURA { get; set; }
        public DbSet<MENU_ROL> MENU_ROL { get; set; }
        public DbSet<OSDDMW_DIAGRAMS> OSDDMW_DIAGRAMS { get; set; }
        public DbSet<PROFESIONAL> PROFESIONAL { get; set; }
        public DbSet<REPORT_MENSUAL> REPORT_MENSUAL { get; set; }
        public DbSet<ROL> ROL { get; set; }
        public DbSet<SERV_DETALLE> SERV_DETALLE { get; set; }
        public DbSet<SERVICIO> SERVICIO { get; set; }
        public DbSet<SUCURSAL> SUCURSAL { get; set; }
        public DbSet<TICKET> TICKET { get; set; }
        public DbSet<TIPO_CAP> TIPO_CAP { get; set; }
        public DbSet<USUARIO> USUARIO { get; set; }
        public DbSet<VISITA_TERR> VISITA_TERR { get; set; }
    
        public virtual int SP_ACTIVATE_TICKET(Nullable<decimal> v_ID_TICKET)
        {
            var v_ID_TICKETParameter = v_ID_TICKET.HasValue ?
                new ObjectParameter("V_ID_TICKET", v_ID_TICKET) :
                new ObjectParameter("V_ID_TICKET", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_ACTIVATE_TICKET", v_ID_TICKETParameter);
        }
    
        public virtual int SP_CREAR_TICKET(Nullable<System.DateTime> v_FECHA_CREACION_TICKET, Nullable<System.DateTime> v_FECHA_CIERRE_TICKET, Nullable<decimal> v_ID_ESTADO, Nullable<decimal> v_ID_USUARIO, string v_DESCRIPCION, Nullable<decimal> v_ID_PROFESIONAL, string v_SOLUCION)
        {
            var v_FECHA_CREACION_TICKETParameter = v_FECHA_CREACION_TICKET.HasValue ?
                new ObjectParameter("V_FECHA_CREACION_TICKET", v_FECHA_CREACION_TICKET) :
                new ObjectParameter("V_FECHA_CREACION_TICKET", typeof(System.DateTime));
    
            var v_FECHA_CIERRE_TICKETParameter = v_FECHA_CIERRE_TICKET.HasValue ?
                new ObjectParameter("V_FECHA_CIERRE_TICKET", v_FECHA_CIERRE_TICKET) :
                new ObjectParameter("V_FECHA_CIERRE_TICKET", typeof(System.DateTime));
    
            var v_ID_ESTADOParameter = v_ID_ESTADO.HasValue ?
                new ObjectParameter("V_ID_ESTADO", v_ID_ESTADO) :
                new ObjectParameter("V_ID_ESTADO", typeof(decimal));
    
            var v_ID_USUARIOParameter = v_ID_USUARIO.HasValue ?
                new ObjectParameter("V_ID_USUARIO", v_ID_USUARIO) :
                new ObjectParameter("V_ID_USUARIO", typeof(decimal));
    
            var v_DESCRIPCIONParameter = v_DESCRIPCION != null ?
                new ObjectParameter("V_DESCRIPCION", v_DESCRIPCION) :
                new ObjectParameter("V_DESCRIPCION", typeof(string));
    
            var v_ID_PROFESIONALParameter = v_ID_PROFESIONAL.HasValue ?
                new ObjectParameter("V_ID_PROFESIONAL", v_ID_PROFESIONAL) :
                new ObjectParameter("V_ID_PROFESIONAL", typeof(decimal));
    
            var v_SOLUCIONParameter = v_SOLUCION != null ?
                new ObjectParameter("V_SOLUCION", v_SOLUCION) :
                new ObjectParameter("V_SOLUCION", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_CREAR_TICKET", v_FECHA_CREACION_TICKETParameter, v_FECHA_CIERRE_TICKETParameter, v_ID_ESTADOParameter, v_ID_USUARIOParameter, v_DESCRIPCIONParameter, v_ID_PROFESIONALParameter, v_SOLUCIONParameter);
        }
    
        public virtual int SP_DESACTIVATE_TICKET(Nullable<decimal> v_ID_TICKET)
        {
            var v_ID_TICKETParameter = v_ID_TICKET.HasValue ?
                new ObjectParameter("V_ID_TICKET", v_ID_TICKET) :
                new ObjectParameter("V_ID_TICKET", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_DESACTIVATE_TICKET", v_ID_TICKETParameter);
        }
    
        public virtual int SP_UPDATE_TICKET(Nullable<decimal> v_ID_TICKET, Nullable<System.DateTime> v_FECHA_CREACION_TICKET, Nullable<System.DateTime> v_FECHA_CIERRE_TICKET, Nullable<decimal> v_ID_ESTADO, Nullable<decimal> v_ID_USUARIO, string v_DESCRIPCION, Nullable<decimal> v_ID_PROFESIONAL, string v_SOLUCION)
        {
            var v_ID_TICKETParameter = v_ID_TICKET.HasValue ?
                new ObjectParameter("V_ID_TICKET", v_ID_TICKET) :
                new ObjectParameter("V_ID_TICKET", typeof(decimal));
    
            var v_FECHA_CREACION_TICKETParameter = v_FECHA_CREACION_TICKET.HasValue ?
                new ObjectParameter("V_FECHA_CREACION_TICKET", v_FECHA_CREACION_TICKET) :
                new ObjectParameter("V_FECHA_CREACION_TICKET", typeof(System.DateTime));
    
            var v_FECHA_CIERRE_TICKETParameter = v_FECHA_CIERRE_TICKET.HasValue ?
                new ObjectParameter("V_FECHA_CIERRE_TICKET", v_FECHA_CIERRE_TICKET) :
                new ObjectParameter("V_FECHA_CIERRE_TICKET", typeof(System.DateTime));
    
            var v_ID_ESTADOParameter = v_ID_ESTADO.HasValue ?
                new ObjectParameter("V_ID_ESTADO", v_ID_ESTADO) :
                new ObjectParameter("V_ID_ESTADO", typeof(decimal));
    
            var v_ID_USUARIOParameter = v_ID_USUARIO.HasValue ?
                new ObjectParameter("V_ID_USUARIO", v_ID_USUARIO) :
                new ObjectParameter("V_ID_USUARIO", typeof(decimal));
    
            var v_DESCRIPCIONParameter = v_DESCRIPCION != null ?
                new ObjectParameter("V_DESCRIPCION", v_DESCRIPCION) :
                new ObjectParameter("V_DESCRIPCION", typeof(string));
    
            var v_ID_PROFESIONALParameter = v_ID_PROFESIONAL.HasValue ?
                new ObjectParameter("V_ID_PROFESIONAL", v_ID_PROFESIONAL) :
                new ObjectParameter("V_ID_PROFESIONAL", typeof(decimal));
    
            var v_SOLUCIONParameter = v_SOLUCION != null ?
                new ObjectParameter("V_SOLUCION", v_SOLUCION) :
                new ObjectParameter("V_SOLUCION", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_UPDATE_TICKET", v_ID_TICKETParameter, v_FECHA_CREACION_TICKETParameter, v_FECHA_CIERRE_TICKETParameter, v_ID_ESTADOParameter, v_ID_USUARIOParameter, v_DESCRIPCIONParameter, v_ID_PROFESIONALParameter, v_SOLUCIONParameter);
        }
    }
}
