//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NMADesk.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class PROFESIONAL
    {
        public PROFESIONAL()
        {
            this.AGENDA = new HashSet<AGENDA>();
            this.TICKET = new HashSet<TICKET>();
        }
    
        public decimal RUT_PROF { get; set; }
        public string DV_PROF { get; set; }
        public string NOM_PROF { get; set; }
        public string AP_PROF { get; set; }
        public string MAIL_PROF { get; set; }
        public decimal TEL_PROF { get; set; }
        public decimal EMPRESA_RUT_EMP { get; set; }
        public string STAT_PROF { get; set; }
    
        public virtual ICollection<AGENDA> AGENDA { get; set; }
        public virtual EMPRESA EMPRESA { get; set; }
        public virtual ICollection<TICKET> TICKET { get; set; }
    }
}
