//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NMADesk.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class REPORT_MENSUAL
    {
        public decimal ID_REPORT { get; set; }
        public string CLIENTE_REP { get; set; }
        public decimal CANT_VISITA { get; set; }
        public decimal CANT_CAP { get; set; }
        public decimal CANT_ASES { get; set; }
        public decimal CANT_LLAM { get; set; }
        public string NUEVAS_IMPL { get; set; }
        public decimal CANT_ACCID { get; set; }
        public decimal CANT_MULT { get; set; }
        public decimal MONTO_TOTAL_MUL { get; set; }
    }
}
