//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NMADesk.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class SERV_DETALLE
    {
        public SERV_DETALLE()
        {
            this.CAPACITACION = new HashSet<CAPACITACION>();
            this.VISITA_TERR = new HashSet<VISITA_TERR>();
            this.ASESORIA = new HashSet<ASESORIA>();
        }
    
        public decimal ID_SERV_DETALLE { get; set; }
        public decimal RUT_CLI_SERV { get; set; }
        public decimal RUT_PROF_SERV { get; set; }
        public string LUGAR { get; set; }
        public string TIPO_SERV { get; set; }
        public decimal EN_CONTRATO { get; set; }
        public decimal SERVICIO_ID_SERV { get; set; }
    
        public virtual ICollection<CAPACITACION> CAPACITACION { get; set; }
        public virtual SERVICIO SERVICIO { get; set; }
        public virtual ICollection<VISITA_TERR> VISITA_TERR { get; set; }
        public virtual ICollection<ASESORIA> ASESORIA { get; set; }
    }
}
