//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NMADesk.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class SERVICIO
    {
        public SERVICIO()
        {
            this.SERV_DETALLE = new HashSet<SERV_DETALLE>();
        }
    
        public decimal ID_SERV { get; set; }
        public string NOM_SERV { get; set; }
        public decimal COSTO_SERV { get; set; }
        public decimal CLIENTE_RUT_CLI { get; set; }
        public decimal AGENDA_ID_AGENDA { get; set; }
    
        public virtual AGENDA AGENDA { get; set; }
        public virtual CLIENTE CLIENTE { get; set; }
        public virtual ICollection<SERV_DETALLE> SERV_DETALLE { get; set; }
    }
}
