//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NMADesk.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class TICKET
    {
        public decimal ID_TICKET { get; set; }
        public System.DateTime FECHA_CREACION_TICKET { get; set; }
        public System.DateTime FECHA_CIERRE_TICKET { get; set; }
        public decimal ID_ESTADO { get; set; }
        public decimal ID_USUARIO { get; set; }
        public decimal ID_TIPO { get; set; }
        public string DESCRIPCION { get; set; }
        public decimal ID_PROFESIONAL { get; set; }
        public string SOLUCION { get; set; }
    
        public virtual ESTADO ESTADO { get; set; }
        public virtual PROFESIONAL PROFESIONAL { get; set; }
        public virtual TIPO_TICKET TIPO_TICKET { get; set; }
        public virtual USUARIO USUARIO { get; set; }
    }
}
