//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NMADesk.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class TIPO_TICKET
    {
        public TIPO_TICKET()
        {
            this.TICKET = new HashSet<TICKET>();
        }
    
        public decimal ID_TIPO { get; set; }
        public string NOMBRE { get; set; }
    
        public virtual ICollection<TICKET> TICKET { get; set; }
    }
}
