//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NMADesk.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class USUARIO
    {
        public USUARIO()
        {
            this.TICKET = new HashSet<TICKET>();
        }
    
        public decimal ID_USER { get; set; }
        public string NOM_USER { get; set; }
        public string AP_USER { get; set; }
        public string MAIL_USER { get; set; }
        public decimal TELM_USER { get; set; }
        public string STATUS_USER { get; set; }
        public decimal ROL_ID_ROL { get; set; }
        public string PASSWD { get; set; }
        public string PASSWD2 { get; set; }
    
        public virtual ROL ROL { get; set; }
        public virtual ICollection<TICKET> TICKET { get; set; }
    }
}
