//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NMADesk.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class VISITA_TERR
    {
        public VISITA_TERR()
        {
            this.CHECKLIST = new HashSet<CHECKLIST>();
        }
    
        public decimal ID_VISITA { get; set; }
        public System.DateTime FECHA_VISITA { get; set; }
        public string TIPO_VISITA { get; set; }
        public string RESOL_VISIT { get; set; }
        public decimal SERV_DETALLE_ID_SERV_DETALLE { get; set; }
    
        public virtual ICollection<CHECKLIST> CHECKLIST { get; set; }
        public virtual SERV_DETALLE SERV_DETALLE { get; set; }
    }
}
